safe:        false
auto:        false
server:      false
server_port: 4000
baseurl:    /
url: http://localhost:4000

source:      .
destination: ./_site
plugins:     ./_plugins

future:      true
lsi:         false
pygments:    false
markdown:    maruku
permalink:   date

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex

rdiscount:
  extensions: []

kramdown:
  auto_ids: true,
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false
  
  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style

navigation:
- header: Big Stuff
- text: Authentication
  url: authentication.html
- text: Application Proxy
  url: application_proxy.html
- text: Cart Manipulation
  url: cart_manipulation.html
- header: Billing
- text: Overview
  url: billing_overview.html
- text: Application Charges
  url: application_charges.html
- text: Recurring Application Charges
  url: recurring_application_charges.html
- header: API Reference
- text: Article
  url: article.html
- text: Asset
  url: asset.html
- text: Blog
  url: blog/html
- text: Cart
  url: cart.html
- text: Collect
  url: collect.html
- text: Comment
  url: comment.html
- text: Country
  url: country.html
- text: Custom Collection
  url: custom_collection.html
- text: Customer
  url: customer.html
- text: Customer Group
  url: customer_group.html
- text: Event
  url: event.html
- text: Fulfillment
  url: fulfillment.html
- text: Metafield
  url: metafield.html
- text: Order
  url: order.html
- text: Page
  url: page.html
- text: Product
  url: product.html
- text: Product Image
  url: product_image.html
- text: Product Variant
  url: product_variant.html
- text: Product Search Engine
  url: product_search_engine.html
- text: Province
  url: provice.html
- text: Redirect
  url: redirect.html
- text: Script Tag
  url: script_tag.html
- text: Shop
  url: shop.html
- text: Smart Collection
  url: smart_collection.html
- text: Theme
  url: theme.html
- text: Transactions
  url: transactions.html
- text: Webhook
  url: webhook.html